# Build settings
url: chocof.github.io
port: 4000
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]
markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Fotis Tsokos"
description: "MEng Computer Systems and Networks Engineering"
author:      "Fotis Tsokos"
