#-------------------------------
# General Site Settings

menu:
- {name: 'Home',    url: ''}
- {name: 'Projects', url: 'projects'}
- {name: 'Blog',     url: 'blog'}
# - {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Development of a Software Defined Perimeter',   url: 'sdp'}
- {name: 'Al Pastor: NIDS Dataset Generator',   url: 'al_pastor'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/chocof'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/fotis-tsokos-5bb557ba/'}
- {icon: 'envelope',  link: 'mailto:mailto:fotisdtsokos@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Fotis Tsokos: Personal Website'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
